[package]
name = "atrium-portal-secret"
description = "Encrypted native Secret portal implementation for Tessera"
readme = "README.md"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
atrium-portal-runtime.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zbus.workspace = true
